In [5]:
import numpy as np
a1 = np.zeros((2,3))
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
a2 = np.ones((2,3))
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
a3 = np.full((5,2),22)
print(a3)

[[22 22]
 [22 22]
 [22 22]
 [22 22]
 [22 22]]


In [15]:
ar = np.arange(2,10,2)
print(ar)

[2 4 6 8]


In [20]:
ar = np.random.randint(2,20,5)
print(ar)

[ 7  2  5 16  5]


In [31]:
ar = np.array([12,23,34,45,56,67,78,89,90,99])
print(ar.shape)
print(len(ar))
ar.shape = (5,2)
print(ar.shape)
print(ar)

(10,)
10
(5, 2)
[[12 23]
 [34 45]
 [56 67]
 [78 89]
 [90 99]]


In [38]:
ar1 = np.array([10,20,30,40,50])
ar2 = np.array([60,70,80,90,100])
aa = np.vstack((ar1,ar1))
print(aa)

[[10 20 30 40 50]
 [10 20 30 40 50]]


In [39]:
ar1 = np.array([10,20,30,40,50])
ar2 = np.array([60,70,80,90,100])
aa = np.hstack((ar1,ar1))
print(aa)

[10 20 30 40 50 10 20 30 40 50]


In [41]:
ar1 = np.array([10,20,30,40,50])
ar2 = np.array([60,70,80,90,100])
aa = np.column_stack((ar1,ar2))
print(aa)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


In [49]:
ar3 = np.array([12,34,45,55])
ar4 = np.array([12,22,334,34,33])
ara = np.intersect1d(ar3,ar4)
print(ara)

[12 34]


In [54]:
ara1 = np.array([1,2,3,4,5,6])
ara2 = np.array([12,23,34,45,44,1,2,3,4])
print(np.setdiff1d(ara2,ara2))

[]


In [61]:
ar5 = np.array([12,10,20,30,40])
ar6 = np.array([50,60,70,80,90])
a = np.sum([ar5,ar6],axis = 1)
print(a)

[112 350]


In [69]:
a1 = np.array([10,20,30,40,50])
a  = (a1//3)
print(a)

[ 3  6 10 13 16]


In [73]:
a = np.array([10,20,30,45,33,50,60,70])
mean_numpy = np.mean(a)
print(mean_numpy)
print(np.median(a))
print(np.std(a))

39.75
39.0
18.952242611363964


In [79]:
aar22 = np.array([10,20,30,40,50])
save_of = np.save('my_numpy',aar22)
load_of = np.load('my_numpy.npy')
print(save_of)
print(load_of)


None
[10 20 30 40 50]
